### ISSUE TITLE
Large blank area on mobile - forceHeight:false, Mobile, Relative Mode

### ISSUE THREAD

**Issue by ghost** [Prinzhorn/skrollr#104]
Hello,

I have read issue 58 and 61 and I have a version of the bug in issue 61.

When viewed on an iPad or iPhone there is a large blank area below the content even though forceHeight is set to false.

The large blank area appears to be the HTML tag from inspecting it in safari.
I have double checked that Twitter Bootstrap is not messing up the HTML tag.

Here is my code:
https://github.com/wkjiv/Mastline-Front-End
This is over my head, any help would be greatly appreciated.

**Comment by mwgdavies** [comment]
Hi @Prinzhorn 

I think I'm getting an instance of this issue. I have set `forceHeight: true`. Desktop is fine and some android devices are fine but iOS seems to add the extra space at the foot of the page.

I tried to hack it with `height: auto !important;` for screens <1023 but this isn't behaving either.

Site is deployed at https://www.techwillsaveus.com/microbit/ (but still to be finished/fixed) Any help would be MUCH appreciated.

Loving skrollr, it has really helped me out. Thank you :)
