### ISSUE TITLE
Chrome performance

### ISSUE THREAD

**Issue by Prinzhorn** [Prinzhorn/skrollr#128]
quote from a chat

> i'm using your skrollr lib on this site, which is in development right now: http://new.vdemenko.ru
> And i viewing it from chrome most of the time, and everything works just fine  and very smooth in chrome until approximately two weeks ago chrome is updated, then it starts to works slower (laggy). And now it's still works slow, even in firefox site works much better than in chrome, but until update it was vice verca. But i didn't change anything in the code that days, because i was bussy on other project.
> I was trying to find any information, writting to google's chrome support, with no luck.
> Did you know what happens with chrome?

**Comment by hirasso** [comment]
Hi there, one year later, chrome still lags a lot (Version 42.0.2311.135 (64-bit), MBP Retina 13 inch).

**Comment by mholt** [comment]
I'm seeing the same issues with Chrome. Not too great on Firefox either, but still better.

**Comment by calluna** [comment]
I found a fix on another thread, it totally worked for me!
(if it totally messes up your styling, as it did for me, just target the parallax parts that give the most problems, like the big images for instance)

I quote:
"use this in the beginnig of your css

*,:before,:after {
-moz-box-sizing:border-box;
-webkit-box-sizing:border-box;
box-sizing:border-box;
-webkit-backface-visibility:hidden;
}
"
See thread:
https://github.com/Prinzhorn/skrollr/issues/551
