### ISSUE TITLE
forceHeight calculation collides with the already forced height

### ISSUE THREAD

**Issue by Prinzhorn** [Prinzhorn/skrollr#216]
From http://stackoverflow.com/questions/16619771/how-to-avoid-skroll-js-to-create-extra-space-in-footer

When `forceHeight` is `true`, which is the default, then skrollr makes sure you can scroll far enough.

But when you resize the browser the already forced height collides with the calculations for the new height.

In particular, when calling `_getDocumentHeight()` the height may be reported larger than it is, because it's still being forced (https://github.com/Prinzhorn/skrollr/blob/master/src/skrollr.js#L1276).

Solution: Reset the height to `auto` right before we're calculation the target height we need to force.

**Comment by tkelling** [comment]
Thanks for the plugin and the fix. Worked for me.
