### ISSUE TITLE
Add scroll event to the element inside #skrollr-body on iPhone

### ISSUE THREAD

**Issue by resarahman** [Prinzhorn/skrollr#226]
Hi There,

Is there any way to add scroll event to the element inside #skrollr-body ?
example: I have a menu that show list of pages with overflow:auto;height:230px; but since this element inside #skrollr-body, the menu can't be scrolled, instead it scroll all elements as #skroll-body scrolling.

Regards,

**Comment by Leooo** [comment]
Any way to code a "data-skrollr-ignore" or close and disable skrollr touch events on elements inside this div? (code should be close to rxTouchIgnoreTags I suppose)?
