### ISSUE TITLE
Scrollr inside a div

### ISSUE THREAD

**Issue by loopingGIT** [Prinzhorn/skrollr#232]
Hi there, i wonder if it is possible to use Scrollr just for a div and not the body, something like $('myElement').skrollr.init();

thanks.

**Comment by RomanGotsiy** [comment]
+1 For this feature request.

> Did anyone try the changes in IE 8 and more important on mobile? And "it seems to work" is not what I mean. For example APIs like setScrollTop should also work.

Why not just mark this feature in docs as **experimental** or **IE9+** or even **breaksSetScrollTop** :) (or something similar)?

**Comment by anasnakawa** [comment]
+1 for this feature,
since in some platforms like Microsoft SharePoint, disables the default scrolling behavior, and append the whole page content in a scrollable div.
