### ISSUE TITLE
Background-Image: The Background doesn't change

### ISSUE THREAD

**Issue by Eurydicee** [Prinzhorn/skrollr#244]
Hi prinzhorn,
i have a simple problem. The background of my div doesn't change.

*div data-20="background-image:url(ani/reden.png);" data-500="background-image:url(ani/normal.png);" id="normal"></div>

i have used the shim.html, and changed nothing. i only put the div between *div id="skrollr-body"></div> and add some css style:
# girl {

```
position:fixed;
width:500px;
height:600px;
top: 200px;
left:100px;
background:url(ani/standart.png);
```

}
# normal {

```
position:absolute;
width: 192px;
height: 217px;
top:178px;
left:144px;
```

}

i changed the < to a \* purposely. sry, im new here.

If i open the console in chrome, is see the js working. but nothing happens...
firefox: nothing happens.
chrome: the speak.png 'flickers'.

where is the mistake? i have really tried everything, but nothing works.
i hope you can help me. thank you.

**Comment by webdesignervijay** [comment]
Hello
Prinzhorn Sir,

This is vijay shinde from pune. I like your plugin for scrolling animation

but i have one query that how to set keyframe animation by scrollr.js

see the below link

http://codepen.io/rachelnabors/pen/gcump

I want  to animate on scrolling so how I can Do
