### ISSUE TITLE
iOS scrolling on top of iframes (YouTube)

### ISSUE THREAD

**Issue by moemos** [Prinzhorn/skrollr#307]
Hi,

I built an Skrollr site with several YouTube videos embedded. It is exclusively for Apple iPad.
Everythink works great until I try to swipe/scroll on top of a YT iframe. Instead of the "#skrollr-body" wrapper the whole native site is scrolling and all scroll-positions will be out of sync. :(

Any suggestions for fixing this? At least can I disable scrolling for those iframes?

Thanks!

**Comment by henryson** [comment]
This is still a big problem for me and none of the above solves it. I'm amazed that not more people has written about this issue. I expect it to be quite common to embed youtube videos on pages using the Skrollr lib. For me there is 2 problems. 1. Unable to scroll video/iframe (sometimes fills whole mobile screen). 2. Unable to start the video (iPhone & iPad). I noticed this thread was closed, should I post in a new thread or can it be opened again? Cheers, Josef

**Comment by Prinzhorn** [comment]
> I noticed this thread was closed, should I post in a new thread or can it be opened again?

I don't know of any perfect solution to this. Having an overlay is the only option that kind of works.

**Comment by jaylathia** [comment]
But does the video controls work when an overlay is  placed above the iframe.

**Comment by Prinzhorn** [comment]
> But does the video controls work when an overlay is placed above the iframe.

No and actually I found that even the overlay won't work because you can't have a custom play button on iOS. I don't have a solution.
