### ISSUE TITLE
iOS: Locked scroll

### ISSUE THREAD

**Issue by nearestnabors** [Prinzhorn/skrollr#311]
Hi there! I'm using skrollr with waypoints.js for a project. It works great on Chrome and Safari, but sadly, in iOS Safari, the screen "locks" (I believe someone has had this issue before). I'm presenting two instances of the same code in action for your observation.

The full project (click the rabbit hole to "fall into" the skrollr portion): http://rachelnabors.com/alice-in-videoland/book/

And just the hole sequence: http://codepen.io/rachelnabors/pen/AeEHw

Both exhibit similar symptoms.

Am I missing something, or is there a real issue here?

**Comment by codedcontainer** [comment]
@rachelnabors If it really bothers you then you can do a conditial statement to see if you are in mobile. If not then run skrollr. @Prinzhorn I tried to add #skrollr-body to my main body and this did not work and mobile was still frozen. I had to hack this together and get this to work. 

```
if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
}
else { 
    skrollr.init({
    beforerender: function(data) {
        return data.curTop > data.lastTop;
    }
});
}
```
