### ISSUE TITLE
turn object 180 degrees before scroll up?

### ISSUE THREAD

**Issue by kamiblue** [Prinzhorn/skrollr#421]
Hi,

Wonderful plug-in!--I just have a question--I have a plane fly across my screen and it works fine scrolling down--However, if one scrolls back up it flies backward-so I was wondering if there was a way to reverse the image on done?
img id="fleetweek" src="img/fleetweek.png" width="5764" height="456" alt="fleetweek plane" class="fleet" data-1260="transform:scale(1);left:250%; "data-1860="transform:scale(2);left:-1200%;"

Thanks,
--Yvette

**Comment by xavierartot** [comment]
Nice, but we don't have interpolation with this!
