### ISSUE TITLE
Fullpage.js compatibility

### ISSUE THREAD

**Issue by obojdi** [Prinzhorn/skrollr#444]
Fullpage.js allows you to create a long slide with inner vertical scroll. I've been trying to add some skrollr effects to blocks inside that slide but seems to have conflict with a third-party plugin slimscroll.js. Skrollr just doesn't work. Eternal thanks for any idea

**Comment by alvarotrigo** [comment]
Just use the fullPage.js option `scrollBar:true`. 
From [fullPage.js FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions#parallax-doesnt-work-with-fullpagejs):

>** Parallax doesn't work with fullpage.js.**
**Short answer:** use the scrollBar:true option for fullPage.js or autoScrolling:false if you don't want to use the auto-scrolling feature.

> **Explanation:** Parallax, as well as many other plugins which depends on the scrolling of the site, listens the scrollTop property of javascript. fullPage.js doesn't actually scroll the site but it changes the top or translate3d property of the site. Only when using the fullPage.js option scrollBar:true or autoScrolling:false it will actually scroll the site in a way it is accessible for the scrollTop property.

**Comment by TrySound** [comment]
@obojdi  You may try my realization [skrollr-decks](https://github.com/TrySound/skrollr-decks)
