### ISSUE TITLE
Can't interpolate exception thrown when transition between colors is needed

### ISSUE THREAD

**Issue by siemiatj** [Prinzhorn/skrollr#63]
Colors should be handled differently than the current way:

if(val1.length !== val2.length) {

as one may define transition like :

```
            data-1020="background-color: #372941"
            data-1500="background-color: white"
```

or

```
            data-1020="background-color: #372941"
            data-1500="background-color: #fff"
```

and not only lengths are different then, but also #ffffff is treated as :

["#ffffff"]

instead of 

["#?", "ffffff"]

**Comment by guardianelfjack** [comment]
I just want to change background image.
data-611="background-image: url(images/allbg.png);"
data-612="background-image: url(images/bg2.jpg);
i tested 10 times(i mean scroll up and scroll down) and it is ok,but over 10 times it is not working.i can't scroll.
