### ISSUE TITLE
modify one element depending on position of another

### ISSUE THREAD

**Issue by ValeryVS** [Prinzhorn/skrollr#655]
Is there a way to do this?

For example
< div id="block1" data-affect="#block2" data-top="opacity:0" data-bottom="opacity:1"></div >
< div id="block2"></div >

Animate "opacity" of block2, between "top" and "bottom" of block1.

I can make JS function, that count position of block1 in pixels and add
data-123="opacity:0" data-456="opacity:1"
to block2 (and invoke this function on window resize with skrollr update).

But may be there is a simplier way?
Or it will be idea to do such way.

**Comment by Prinzhorn** [comment]
It's `data-anchor-target`, see last paragraphs in https://github.com/Prinzhorn/skrollr#relative-mode-or-viewport-mode
