### ISSUE TITLE
IE9 + tablet issues

### ISSUE THREAD

**Issue by IstvanLovas** [Prinzhorn/skrollr#657]
Hi there! I am pretty new here but i am in need of some help. I have created a website and used the Skrollr library for parallax scroll but it seems i have made some silly mistakes as the website do not work in tablets (screen locks) and have a messed up html in IE9. I have some clues that it might be the fixed positioning on one section of the website but the client insists to leave it as it is.
Can you please have a a look and share Your opinions?! I really appreciate Your help and thank You in advance!
here is the website: www.graphicoutlines.com

**Comment by Prinzhorn** [comment]
Did you find a solution other may benefit from or did you give up? If there's something useful to share, don't hesitate.

**Comment by IstvanLovas** [comment]
Hi Prinzhorn!

Yes, it turned out that taking out the fixed positioned sections solves the problem. Even putting the fixed positioned elements outside of skrollr, did not work in IE9 (it works but messed up the entire layout). However it would be super awesome if fixed positioning would be better supported. For IE9, I have also had trouble with enquire.js so i left it out and now it works smooth. I do not understand what could have gone wrong with enquire.js though?! Any idea?

**Comment by Prinzhorn** [comment]
> However it would be super awesome if fixed positioning would be better supported

Not sure how. You can't have fixed positioned elements inside transformed elements as per CSS spec. That's the problem http://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/

> For IE9, I have also had trouble with enquire.js so i left it out and now it works smooth. I do not understand what could have gone wrong with enquire.js though?! Any idea?

I've never used enquire.js and I don't know why it should conflict with skrollr.
