### ISSUE TITLE
Firefox, Safari, Explorer has a problem with elements with negative margin-top values

### ISSUE THREAD

**Issue by tommibv** [Prinzhorn/skrollr#658]
Hi, I made a page with elements that moves up while scrolling but it works only on chrome, it seems like at a certain scroll the elements stops moving.

here is the link: http://caparzo.cuculus.it/Altrepagine/BORGOSCOPETO/index.html

works on chrome  39.0.2171.95 m Win 8.1
thanks

**Comment by Prinzhorn** [comment]
You're mixing `px` and `%`

**Comment by tommibv** [comment]
no, the problem was the relative positioning of the div .col1
