### ISSUE TITLE
Render when scrolling inside keyframe

### ISSUE THREAD

**Issue by coreymcollins** [Prinzhorn/skrollr#661]
I have a function firing when I reach the 'data0TopBottom' keyframe while scrolling down.  A piece of content slides out of view once a user scrolls to this point.

I would like to be able to slide that content back in place when the user scrolls up.  However, the function won't fire again until I enter a new keyframe.  Is there a way to listen to scrolling while within a specific keyframe?

Here's a gist of the code I'm working with currently to get an idea of what I have in place: https://gist.github.com/coreymcollins/5692948dde679db6da49

**Comment by Prinzhorn** [comment]
Could you create a very simplified version of the website? Like a demo on jsbin.com? This would be much easier to understand. Also the terminology "between keyframe" should be defined, as a keyframe is exactly one point, there is no between.

Also: the event triggers everytime you skrollr past the keyframe. So if you jump around your `data0TopBottom` (like scrolling 5px up/down around it) you constantly get up/down events.

**Comment by coreymcollins** [comment]
Here's a working codepen: http://codepen.io/coreymcollins/pen/JoWVpp

And an animated gif of the current functionality for the section in question: https://www.dropbox.com/s/jpnbeyw36i26pip/codepen-skrollr.gif?dl=0

The basic thing here is this -

You'll get to the cat in the snow and the "discover our products" text slides up and out of view, which is what I want.  If I scroll up, I would like the text to slide back into view.  This currently does not happen until I hit the "data0TopBottom" keyframe.

Perhaps I'm not using the keyframes properly, but when I do console.log(direction) on line 53, the direction is only written to the log once I scroll past a keyframe.  If I scroll up and down without scrolling past a keyframe, the direction is not continually written.

**Comment by Prinzhorn** [comment]
> Perhaps I'm not using the keyframes properly

Yes. The keyframe event triggers when you scroll past the keyframe. Like arriving at different checkpoints in a game. It's a one-time thing. Firing these constantly defeats their purpose as _events_.

If you want continuous updates use the `render` event, which fires every time skrollr renders because of a changed scroll position (or window resize). You can use the keyframe events to set some flags and act accordingly inside the render event.

**Comment by coreymcollins** [comment]
That's what I figured - as you can see in the Pen above, I'm having some other stuff fire during render; so, I can target that piece of content and slide it back in when its parent has a specific class (probably skrollable-after at that point).

Thanks!
