### ISSUE TITLE
Google Maps v3 breaks Skrollr

### ISSUE THREAD

**Issue by isarmstrong** [Prinzhorn/skrollr#674]
I'm having a "help me Obi Wan Kenobi" moment here.

Adding a Google Maps div on the page - literally anywhere on the page including outside of the skrollr body - cause Skrollr to break. Worse, it's a silent error in the console.

I duplicated the issue in Codepen (literally duplicated, it's almost a copy-paste from my IDE, minus the PHP calls):

With Map:
http://codepen.io/Imperative/pen/f0945c1c44610c156e63ed5b30020826

Without Map:
http://codepen.io/Imperative/pen/e9307d22a1656c0d0b3e32eadd4b8c39

All I did, literally, was remove the map canvas DIV. When it's in, the plugin fails. When it's out, Skrollr works as expected.

I'm under a pretty heavy time crunch at work and I would really really really hate to have to start the parallax portion of the site over again. Can you spot a workaround?

**Comment by leemwilliams** [comment]
Hmmm...nothing obvious. Are you stuck on timing and frequency...I would change the order of the calls and variables, and see if it makes a difference.

**Comment by isarmstrong** [comment]
What I know now, after a lot of debugging effort, is that it's a z-indexing issue. Essentially, that's why the console isn't reporting any bugs - because the JS isn't at fault. This doesn't stop it from being a plugin issue though so I'll keep this open.

In Chrome, if I select #frame-2 and add a z-index of 50, the image leaps to the front and completely covers the map. If I remove the z-index, it stays there.

So something in the way Google Maps v3 inserts itself into the page is causing the parent container's z-index to go haywire.

**Comment by isarmstrong** [comment]
Quick note - the demo I did was only checked in Chrome. My hack of a fast paste means it doesn't always render right in alternate browsers (not a problem in production)

**Comment by Prinzhorn** [comment]
Maybe I'm missing something, but what do you mean with "cause Skrollr to break"? There's not a single animation on the page, how do you see that it broke?

**Comment by isarmstrong** [comment]
Quick answer - you're right, I had simplified it to a point where Skrollr was no longer a factor. Too long looking at the same problem.

Aside - I needed to add a translate-z to the containers and tweak a pair of z-index values. The formerly 'broken' version works fine now.

Moral of the story: don't skip lunch and try to keep coding.
