### ISSUE TITLE
AnimateTo() question

### ISSUE THREAD

**Issue by gerbenvandijk** [Prinzhorn/skrollr#676]
Hi there would the following be possible by using animateTo():

Disable physical scrolling in general, but when the users scrolls, Skrollr incrementally animates to different positions (keeping direction in mind)?

I've tried to build this myself, but Skrollr seems to disable me from blocking the scroll functionality as it uses is internally.

We'd like this feature for older iOs and adroid devices, that don't have a proper scroll event and hence jumps from state to state. Also, it's something we're considering to do for all users as it guides them in a bit more controlled way through our storyline.

Thanks!

**Comment by Prinzhorn** [comment]
a long time ago there was a demo (for desktop) which did this https://github.com/Prinzhorn/skrollr/commit/c3e07540aa694c1b9310ed2e207e14e3e71207be maybe you find it useful. I personally don't like when websites do this and feel offended and ctrl+w.

**Comment by gerbenvandijk** [comment]
:+1: thanks!
