### ISSUE TITLE
Incorrect URL, skrollr remove "0" in url

### ISSUE THREAD

**Issue by SilverKenn** [Prinzhorn/skrollr#679]
I have this HTML tag on the back-end,

```<div class="section-4" data-0="background-image:url(/wp-content/uploads/2015/02/fullwidth-box-tail.gif);" data-anchor-target="#home">```

Scroll Output is something like this. 

```<div class="section-4 skrollable skrollable-after" data-0="background-image:url(/wp-content/uploads/2015/02/fullwidth-box-tail.gif);" data-anchor-target="#home" style="background-image: url(/wp-content/uploads/2015/2/fullwidth-box-tail.gif);">```

you'll see the url is ```/wp-content/uploads/2015/02/fullwidth-box-tail.gif```
but scroll change it to ```/wp-content/uploads/2015/2/fullwidth-box-tail.gif``` when implementing the background image style

Any help would be appreciated

**Comment by Prinzhorn** [comment]
https://github.com/Prinzhorn/skrollr/issues/668
