### ISSUE TITLE
data-end not working as expected

### ISSUE THREAD

**Issue by mikeebee** [Prinzhorn/skrollr#682]
Hi, 

I feel like the code I have should be working but it just isn't.

```
<footer class="footer data-end="bottom: 0;" data--500-end="bottom: -200px;">
```

As I understand it, this means that when you reach the end of the document, the footer should have bottom: 0; and when the document is 500px before the end (when the footer starts being revealed) it should have bottom: -200px;

I'm trying to have it subtly 'parallax' in, similar to the header image but nothing is happening with those values.

[Here is the example in question](http://mikeebee.com/other/skrollr-issue/html/home.php) - header is fine, look at the blue footer.

Thanks!

**Comment by Prinzhorn** [comment]
You need a unit for the first value.

```html
<footer class="footer data-end="bottom: 0px;" data--500-end="bottom: -200px;">
```
But the real problem is that you never reach `data-end` because of `body {height:100% !important}` in combination with the fact that you're moving elements using `top` and `margin-top`. So everything is a mess kind of.

**Comment by mikeebee** [comment]
Ah, that explains it!

I was in the middle of posting an updated example that wasn't working but I noticed it was working on the server but not locally. Changed the script to initialise on window.load rather than document ready and it's working as expected. I think that has been the main reason my experimentation has not been yielding results.

Thanks for your help!
