### ISSUE TITLE
mobile  compatibility

### ISSUE THREAD

**Issue by baisusua** [Prinzhorn/skrollr#683]
在移动端使用skrollr使用锚点定位后无法滑动网页
<a href="#contact">Contact Me</a>//button
<section id="contact"></section>//target
 var pos = $("#contact").offset().top;
 $("html,body").animate({scrollTop: pos}, 1000);
return false;

**Comment by Prinzhorn** [comment]
https://github.com/Prinzhorn/skrollr#animatetotop-options
