### ISSUE TITLE
SVG with this plugin

### ISSUE THREAD

**Issue by mamamamia** [Prinzhorn/skrollr#685]
Hi there,

First thanks for the author making this plugin with time and effort. 

I would like to know if this could make the repeat effect when scrolling on page as shown in the following examples: 
<a href="http://gardenestudio.com.br/" title="" target="_blank">example one</a>
<a href="http://onedesigncompany.com/approach" title="" target="_blank">example two</a>

For SVG, I think I would use this  <a href="http://codecanyon.net/item/enliven-em-svg-animation-engine-for-wordpress/9666605" title="" target="_blank">function</a>
After finishing the SVG part, could this plugin make the effect as I want in the above examples?

Since I am not familiar with SVG and code, I don't know if it is work....Sorry for making any unclear if I say anything wrong.

Could anyone be generous to let me know how to make such kind of effect on the website if the above means is not work... I don't mind learning with time and effort. 
PS: it is a wordpress website.

Thank you very much!

**Comment by Prinzhorn** [comment]
I is possible (http://prinzhorn.github.io/skrollr/examples/path.html) but requires some SVG knowledge. I don't think you need this SVG Animation Engine though, since the animations will be done by skrollr. You can create SVG with Inkscape.
