### ISSUE TITLE
Skrollr only works locally in Chrome but not when live

### ISSUE THREAD

**Issue by oilmundo** [Prinzhorn/skrollr#687]
Hi,

I have a couple of related issues. My animations work fine in Firefox and IE but only work locally in Chrome, although they do work online in Chrome after resizing. How can this be?  I've seen other threads dealing with the resizing issue and I've added a the debounce / refresh function as suggested but it doesn't work. Maybe I haven't applied this properly as I'm a designer rather than a coder.

I know what is happening is that the animations are firing before they hit the viewport, because if you zoom out

You can view my page on

www.bluebloc.ie/mind

Any help would be greatly appreciated as the launch date is looming and this only became apparent once I made the pages live.

Thanks

**Comment by Prinzhorn** [comment]
> How can this be?

race-conditions. Locally your images load almost instantly. On the web they don't. When you init skrollr some images are missing. Once they are loaded, the meaning of stuff like `data-top` changed, because the new images moved elements in the document down. Refresh skrollr when all images are loaded.

```js
$(window).load(function() { skrollr.get().refresh(); });
```

**Comment by oilmundo** [comment]
Thanks a million Alexander. Tried this and it works.

Regards

Marc

**Comment by sramos14** [comment]
I have a novice question. Where do I put the above code? Do I wrap it in script tags at the bottom near the init skrollr? Please advise. Thank you!

**Comment by Prinzhorn** [comment]
> I have a novice question. Where do I put the above code? Do I wrap it in script tags at the bottom near the init skrollr? Please advise. Thank you!

The code may not apply to your case as the website above is already using jQuery which the code makes use of. If you are using jQuery then you can put the code in a script tag anywhere below the jQuery code. The exact position doesn't matter at all since it just adds an event listener.
