### ISSUE TITLE
forceHeight: false breaks skrollr in webkit browsers

### ISSUE THREAD

**Issue by Sanderha** [Prinzhorn/skrollr#690]
Has anyone experienced this problems? Skrollr is working fine in Firefox, but not in Safari and Chrome, when forceHeight: false is set. It might be a css problem, just can find it.
Skrollr itself does not give any errors in Safari or Chrome, it just doesnt work. 

Anyone know any good ways of debugging this?

**Comment by Prinzhorn** [comment]
> Anyone know any good ways of debugging this?

usually mobile issues can be debugged with emulation in Chrome https://github.com/Prinzhorn/skrollr/wiki/Tips#debugging-mobile

**Comment by Sanderha** [comment]
Found the problem. Somewhere on body and html, overflow-x: hidden was set.
