### ISSUE TITLE
Skip property... is this possible?

### ISSUE THREAD

**Issue by andreimoment** [Prinzhorn/skrollr#692]
I would like to be able to have one of the properties in a data point not be used and instead interpolated based on its neighboring data points.

    data-35p-top="top: 150vh; @show--video-btn: !0;"  << A: top: 150vh
    data-10p-top="top: ???vh; @show--video-btn: !1;"  << B: the top property here should be a function of A and C
    data--0p-top="top: 50vh; @show--video-btn: !1;"  << C: top: 50vh

I imagine a logical notation for point B could be 

        data-10p-top="!top: ANYTHING_HEREvh; @show--video-btn: !1;"

I am using this to trigger a class on a moving element. I would like to trigger at a specific point in the movement, without having to manually calculate the `top` value for this specific data point.

Is this possible?

Note: This is the CSS for the above:

      .button[show--video-btn="0"] & {
        opacity: 0;
        transform: translate(0, 5vh);
      }
      .button[show--video-btn="1"] & {
        opacity: 1;
        transform: translate(0, 0);
      }
      .button[show--video-btn="2"] & {
        opacity: 0;
      }

**Comment by Prinzhorn** [comment]
this is not implemented https://github.com/Prinzhorn/skrollr#filling-missing-values

**Comment by andreimoment** [comment]
I am wondering if it would be possible to implement it? I looked at the code but it's beyond my level of JS. Do you think that this API would be OK?

     data-10p-top="!top: [THIS WILL BE EVALUATED BASED ON NEIGHBORING PROPERTIES]; @show--video-btn: !1;"

If I understand correctly, this would be difficult to implement because currently the code only evaluates neighboring properties, correct?

**Comment by Prinzhorn** [comment]
> If I understand correctly, this would be difficult to implement because currently the code only evaluates neighboring properties, correct?

yes, this happens here https://github.com/Prinzhorn/skrollr/blob/1da1627e80ffb5c569880e4c77845e116905cf9f/src/skrollr.js#L1013 left/right are the two keyframes we are in between at the current scroll position.

This would have to be implemented on a different level. We'd have to interpolate the missing value once the properties are parsed.

> I am wondering if it would be possible to implement it?

well, everything is possible. But I don't have any motivation to implement new features at the moment.

**Comment by andreimoment** [comment]
I understand. Thank you for the quick reply and thank you for this awesome contraption :) I love the simplicity of the API and the speed.
