### ISSUE TITLE
Blank keyframe for an event causes the preceeding keyframe to be hoisted to its place.

### ISSUE THREAD

**Issue by rk** [Prinzhorn/skrollr#693]
Using a block sized 200vh I have an element that starts transitioning at `center-top` and completes by `bottom-center`. I need to trigger a lightbox on a specific keyframe, so I trigger it on the `dataBottomCenter` event. As a courtesy to the user I'm trying to hide the lightbox 15% before/after `bottom-center`.

EG:

```html
<a href="#infoRegion"
data-anchor-target="#infoWrapper"
data-center-top="opacity: 0; transform: translateY(-480px)"
data-15p-bottom-center
data-bottom-center="opacity: 1; transform: translateY(0)"
data--15p-bottom-center
data-emit-events
>...</a>
```

However, when animating the engine behaves as-if the element were defined as:

```html
<a href="#infoRegion"
data-anchor-target="#infoWrapper"
data-center-top
data-15p-bottom-center="opacity: 0; transform: translateY(-480px)"
data-bottom-center="opacity: 1; transform: translateY(0)"
data--15p-bottom-center
data-emit-events
>...</a>
```

This produces a very sudden and brief animation, which should have been correctly staggered with the others moving in concert.

**Comment by Prinzhorn** [comment]
See https://github.com/Prinzhorn/skrollr#filling-missing-values
A workaround would be to use a wrapper element (e.g. a span inside the link)
