### ISSUE TITLE
Can't make skrollr.stylesheets work with Chrome and IE

### ISSUE THREAD

**Issue by tititutu** [Prinzhorn/skrollr#697]
Hello and thank you for this wonderful tool.

I am using SkrollrStylesheet and it works perfectly with Firefox and Safari.
Unfortunately, I can not make it work at all with Chrome and IE on my computer.
It works on line... don't understand...

What is the trick ?

Thank you for your answer!

Best regards.

**Comment by Prinzhorn** [comment]
https://github.com/Prinzhorn/skrollr-stylesheets#external-stylesheets

> Heads up: Since external stylesheets are fetched using AJAX (more like SJACSS, but that's not the point here) the same origin policy applies which prohibits AJAX requests when viewing files using the file:// protocol. Either fire up a local server (e.g. npm install http-server -g && http-server or php -S localhost:8080) or start Chrome using google-chrome --disable-web-security.
