### ISSUE TITLE
animateTo() triggers default scroll event

### ISSUE THREAD

**Issue by qikkeronline** [Prinzhorn/skrollr#699]
Hi there, I have a small issue with isAnimatingTo(). I'd like to cancel it if the user scrolls manually (or clicks anywhere), but the animateTo() function also seems to trigger the default scroll event. Is there a way to get around this? An example of my code to scroll, and to cancel the scroll on click is below:

    // init skrollr
	s = skrollr.init({

		// my options here

	});

	// Scroll to bottom link function
	$(document).on('click','a#tobottom', function(e) {

		s.animateTo(s.getMaxScrollTop(), {duration: s.getMaxScrollTop() - s.getScrollTop()});
		return false;
	    
	});

	// Cancel scroll to bottom on click (todo: make this work on user triggered scroll)
	$(document).on('click', 'a.nav_primary_toggle, a.close_menu, .scroller', function(){

		if(s.isAnimatingTo()){
		
			s.stopAnimateTo();

		}

	});

Thanks for the help :+1:

**Comment by Prinzhorn** [comment]
#251
I guess you need to listen for other events like mousewheel and keypress

**Comment by qikkeronline** [comment]
Thanks, makes sense :+1:
