### ISSUE TITLE
Page Loading Speed

### ISSUE THREAD

**Issue by naumankhan** [Prinzhorn/skrollr#704]
Is there any way that we load images as per page scroll instead of loading all images at once because It is effecting the page load speed when load all images at once. Any idea?

**Comment by Prinzhorn** [comment]
Not skrollr related. Google "lazy load images". There are tons of resources on it. You may need to tweak the solutions to work with skrollr on mobile (don't use the scroll event, use skrollr's "render" event and "getScrollTop")
