### ISSUE TITLE
Skrollr error on iOS / iPad

### ISSUE THREAD

**Issue by E-VANCE** [Prinzhorn/skrollr#708]
I am facing a weird issue with skrollr and it is rendering the mobile version on iPad / iOS utterly useless... Although I am still unsure what might be causing it I am writing here because I closely followed both [the classic example](http://prinzhorn.github.io/skrollr/examples/classic.html) in my first attempt (now even slimmer markup) as well as omitting any "fixed"-values inside the skrollr-body [according to your notes](https://github.com/Prinzhorn/skrollr#what-you-need-in-order-to-support-mobile-browsers).

This demo isn't for the looks, if just edited the CSS to allow for a sufficient height:
http://geyersbach.com/development/ueber-geyersbach

If you compare the desktop-version with the mobile-version then you'll see that the footer is completely cut off. Either I am making a huge mistake regarding my styling or it is a genuine error with skrollr...

Of course I can disable the mobile functionality ([this hack](https://github.com/Prinzhorn/skrollr/issues/265#issuecomment-21426090)) but then again that is what skrollr is supposed to be great for – working on mobile devices :)

Thanks for looking into this!

**Comment by Prinzhorn** [comment]
Shouldn't the footer be inside skrollr-body?
Also did you take a look at the source of the page (which is probably auto generated). Looks weird. There's a `<div id="offset"></div>` before the doctype which causes all kind of weirdness like `<meta>` tags inside your body and an empty `<head>`.

![screenshot from 2015-05-03 09 07 08](https://cloud.githubusercontent.com/assets/679144/7444045/d6d4c8a4-f173-11e4-9a4a-c2987a1dc990.png)

**Comment by E-VANCE** [comment]
Hi Alexander,

yeah, guess the footer should be inside skrollr-body and that was at least a symptom of the problem, I doubt that `<div id="offset"></div>` could really have been causing the issue... Anyhow, I managed to somehow work around the footer-issue and now it is working as intended (well, more or less).

Many thanks for a great script and keep up the good work!

Cheers,
Henning
