### ISSUE TITLE
skroller just work inside element not on body tag

### ISSUE THREAD

**Issue by yahyaoffroad** [Prinzhorn/skrollr#716]
Hi,
   I have create an html template i want to use skrollr on specific container in the middle. when i will go to that container and scroll the mouse then the skrollr animation should work. i have tried  this code
documentElement : "container",
 but skrollr just apply on body.

**Comment by wcu1117** [comment]
You can check these,if the scroll code of CSS conflict the body,just  individual opinion。if you had not do it ,you can try it.

**Comment by yahyaoffroad** [comment]
if do you have any example please share it.

**Comment by Prinzhorn** [comment]
This is not supported https://github.com/Prinzhorn/skrollr/issues/232
