### ISSUE TITLE
s.get is not a function

### ISSUE THREAD

**Issue by Worstkaes** [Prinzhorn/skrollr#725]
Hey, 

recently I get the following error: "Uncaught TypeError: s.get is not a function". At the moment I'm testing and my code looks like this:

```
s = skrollr.init({
   forceHeight: false
});
console.log(s.get());
```

Is there another function instead of get to know if skrollr is initialized?
Because I'm trying something like this on mobile devices:

``` 
if (typeof s.get() != "undefined") {
   s.init().destroy();
}
```

Can someone see where I'm wrong?

Greetings,
Moe

**Comment by Prinzhorn** [comment]
It's `skrollr.get()`. A static method to retrieve the singleton, if any.
