### ISSUE TITLE
using constants as data-values

### ISSUE THREAD

**Issue by zoltanseer** [Prinzhorn/skrollr#728]
Hi. Maybe I'm missing something, but is it possible to use constants for values, too?
For ex:
```
<div data-_foo="_bar"></div>
```
and
```
skrollr.init({
   constants: {
      foo: function () { return 500; },
      bar: function() { return 'top: 200px';}
   }
});
```
It would be pretty helpful, for example when the animation values depends on the screen size.

**Comment by Prinzhorn** [comment]
No, this is basically the oldest feature request #69
