### ISSUE TITLE
Fixed Navigation Scrolling Issue

### ISSUE THREAD

**Issue by andrewkyh** [Prinzhorn/skrollr#729]
Hi,

My site has a fixed navigation bar which will change its background color while scrolling through the browser window. It works on both desktop and mobile device.

After added the Skrollr function, on mobile device the navigation bar is still fixed on top of the browser window, but the background color won't change. The fixed navigation bar also placed outside of the `#skrollr-body` element.

Is it something wrong with my JavaScript code below?

```javascript
jQuery(window).load(function () {
    "use strict";
    var header = jQuery(".navbar");
    jQuery(window).scroll(function () {
        var scroll = jQuery(window).scrollTop();
    
        if (scroll >= 80) {
            header.addClass("navbar-scroll");
        } else {
            header.removeClass("navbar-scroll");
        }
    });
});
```

**Comment by Prinzhorn** [comment]
> Is it something wrong with my JavaScript code below?

Yes. You need to use skrollrs `render` event instead of the native `scroll` event. With skrollr on mobile you won't get native scrolling.

**Comment by andrewkyh** [comment]
After I tried to use Skrollrs `render` event as the code below, it seems like working fine on mobile device. Thank you so much!

```javascript
jQuery(window).load(function () {
    "use strict";
    var header = jQuery(".navbar");
    skrollr.init({
        forceHeight: false,
        smoothScrolling: false,
        render: function (scrollMobile) {
            if (scrollMobile.curTop >= 80) {
                header.addClass("navbar-scroll");
            } else {
                header.removeClass("navbar-scroll");
            }
        }
    });
});
```
