### ISSUE TITLE
Allow skrollr-body to be a selector by CLASS instead of ID

### ISSUE THREAD

**Issue by shamank** [Prinzhorn/skrollr#732]
I'm using it in a JQM project and would be vey useful to be able to select the skrollr-body container via a desirable class or tag attribute instead of being an ID, since IDs may conflict between multiple pages and certains scenarios in JQM. ALso, I'm initializating it in a common "pagecreate" event, so it's a bit frustrating to have to change all project pages to add a custom ID for everyone. Thanks!

**Comment by Prinzhorn** [comment]
Closing in favor of #733
