### ISSUE TITLE
IE 10 and 11 stop scrolling in middle of code

### ISSUE THREAD

**Issue by InspireGroup** [Prinzhorn/skrollr#738]
Hi there

I love using skrollr - it's such a cool method. 
But, I've built a scrolling site which stops working in the middle of my page. Thing is, this only happens on IE 10 and 11. 

It gets to about 1533300, which is almost exactly half of the total value of my page and stops. Just in IE. 

Here's the site: http://reviewsite.inspiregroup.co.nz/manual/BestPac/NEW/index.html 

I've been through and checked it over and over and can't find anything that should be causing this. Any ideas? Would be greatly appreciated. :)
THANK YOU!

**Comment by Prinzhorn** [comment]
This is a **LONG** site. I haven't looked at it in IE, but my guess is that you've reached the maximum scroll length that IE can handle. Try a very simple demo with nothing but a very long body and see if it happens there as well.

On the other hand maybe its coincidence and there's a scripting error happening at that point?

**Comment by InspireGroup** [comment]
Yeah man - it is a long scroller. 
Aaaand it looks like you're right. IE scroll limit is 1533900.
http://stackoverflow.com/questions/18708598/ie-fundamental-limit-of-scrolltop-in-a-large-scrollable-div 

Thanks for pointing me in the right direction. Really wicked tool you made. :)
