### ISSUE TITLE
Whitespace at the bottom of the page

### ISSUE THREAD

**Issue by federicovezzoli** [Prinzhorn/skrollr#745]
I'm using Skrollr inside a site.
On touch devices I've some problems with the page not scrolling completely or showing a white space at the bottom, the white space changes it's height in every page.

Here is the pages:
http://altrosito.it/2015/portfolio/tulikivi/
http://altrosito.it/2015/portfolio/trelaghi-hotel/

I've looked through other posts and I've found that forcing the mobile off works:

    var s = skrollr.init({
	forceHeight: false,
	mobileCheck: function() {
		//hack - forces mobile version to be off
		return false;
	}
    });

But then, the parallax looks really ugly since it's not eased.

The issue appears both on ios (even the ios emulator) and android, not on desktop, not even in the chrome emulation.

thanks

**Comment by Prinzhorn** [comment]
You're not using skrollr anymore, right? Closing then.
