### ISSUE TITLE
Skrollr doesn't work when setting body to 100%?

### ISSUE THREAD

**Issue by EireStudio** [Prinzhorn/skrollr#768]
If I set body to auto, it works, BUT there is a ton of space below the footer?

I have also set **skrollr.init({forceHeight: false});**

There has to be a bug here.

Example site: http://tinyurl.com/qcfj7ld

**Comment by Prinzhorn** [comment]
> Example site: http://tinyurl.com/qcfj7ld
> 
> Internal Server Error
