### ISSUE TITLE
Scroll to

### ISSUE THREAD

**Issue by medinlu** [Prinzhorn/skrollr#770]
Is it possible to tell skrollr once the page is load animate scroll to 1000px position?

I tried scrollTo, and it works on desktop... But it doesn't work on mobile devices...

$(document).ready(function () {
    setTimeout(function() {
        $('body').animate({
            scrollTop: '1000px'
        }, 2000);
    }, 1000 );
});

**Comment by Prinzhorn** [comment]
https://github.com/Prinzhorn/skrollr#animatetotop-options
