### ISSUE TITLE
Stiff transition when using position absolute with transform

### ISSUE THREAD

**Issue by BobWassermann** [Prinzhorn/skrollr#776]
Hi,

I want to use Skrollr on `absolute` positioned elements in combination with `transform`. I basically want to create some kind of parallax.

However, `absolute` positioned elements and `transform` doesn't seem to match, see [example](http://codepen.io/anon/pen/gaxWvj), it behaves really stiff.

Is there any way to make this behave more fluid?

**Update: Safari performance is stiff, Chrome doesn't even move the elements at all.**

**Comment by Prinzhorn** [comment]
> All numeric values have to have the same unit, **even 0 needs a unit**. It's not possible to animate from 5% to 100px. skrollr won't complain, but results are undefined.

https://github.com/Prinzhorn/skrollr#limitations

**Comment by BobWassermann** [comment]
@Prinzhorn That does the trick, thanks!
