### ISSUE TITLE
navigation link to anchor within skrollr-body: cant scroll up after click 

### ISSUE THREAD

**Issue by baskinco** [Prinzhorn/skrollr#861]
Inside skrollr-body I have an <a href="#menuitem"..> that links to a <div id="menuitem"..> further down the page. the link takes the user to the correct area, but then the user cannot scroll up to the top of the page from that point. Maybe skrollr is reading the www.pagename.html#menuitem as its own unique page? Hoping someone can point me in the right direction.  

Thanks,
baskinco

**Comment by robhadfield** [comment]
Interesting... What code are you using to scroll to the anchor point? Is that something you wrote with JQ or part of Skrollr?

**Comment by baskinco** [comment]
Just a straight-up HTML id anchor. 
```
<a href="#menuitem1">Menu Item 1</a>
```
```
<div class="classname" id="menuitem1"></div>
```
Both the menu and the div are inside _skrollr-body_

**Comment by robhadfield** [comment]
Is the code online anywhere? I'm not that familiar with how Skrollr handles scrollTo links.

**Comment by baskinco** [comment]
Realized that there is an entire skrollr library just for menus (js/skrollr.menu.min.js) :) Once I added the library and implemented the data-menu-offset method described [here](https://github.com/Prinzhorn/skrollr-menu), everything worked out just fine. thanks again for your help.

**Comment by robhadfield** [comment]
ha, great!
